# VS Code上でHTTPリクエストを送信し、VS Code上でレスポンスを確認できる「REST Client」拡張の紹介
# https://qiita.com/toshi0607/items/c4440d3fbfa72eac840c#rest-client%E3%81%A8%E3%81%AF

###
#createAction
POST http://localhost:5000/samples
content-type: application/json

{
    "name": "sample"
}


###
#readSamples
GET http://localhost:5000/samples

###
#readSample
GET http://localhost:5000/samples/1

###
#seachSamples
GET http://localhost:5000/samples/search?keyword=Doe


###
#updateAction
PUT http://localhost:5000/samples/2
content-type: application/json

{
    "name": "updated_name"
}

###
#deleteAction
DELETE  http://localhost:5000/samples/3
content-type: application/json