# VS Code上でHTTPリクエストを送信し、VS Code上でレスポンスを確認できる「REST Client」拡張の紹介
# https://qiita.com/toshi0607/items/c4440d3fbfa72eac840c#rest-client%E3%81%A8%E3%81%AF

###
#get_todos
GET http://localhost:5000/todos

###
#get_single_user
GET http://localhost:5000/todos/1

###
#get_single_user
GET http://localhost:5000/todos/111

###
#post_post
POST http://localhost:5000/todos
content-type: application/json

 { 
    "name": "abx"
 }

###
#update_user
PUT http://localhost:5000/todos/1
content-type: application/json

{
    "name": "updated_name",
    "email": "updated_sample@mail.com",
    "role": "normal"
}

###
#delete_user
DELETE  http://localhost:5000/users/a36264ca-3590-cec0-8e6a-98e08b57ef4f
content-type: application/json